//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoTheyKnow
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class sub
    {
        public int subId { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
    
        public virtual kom kom { get; set; }
        public virtual Morele Morele { get; set; }
        public virtual wsei wsei { get; set; }
    }
}
